services:
        db:
                image: mysql:8.0.16
                container_name: db
                environment:
                        MYSQL_ROOT_PASSWORD_FILE: 'root'
                        MYSQL_USER: 'root'
                        MYSQL_PASSWORD_FILE: 'swarna99@GB'
                ports:
                        - 3306:3306
                volumes:
                        - dbdata:/var/lib/mysql
        app:
                depends_on:
                        - db
                build: webapp
                container_name: myapp
                ports:
                        - 5000:80
                volumes:
                        - ./webapp:/var/www/html

volumes:
        dbdata: {}