version: "3"
services:
        db:
                image: mysql:8.0.2
                container_name: db
                environment:
                        MYSQL_ROOT_PASSWORD: 'root'
                        MYSQL_USER: 'root'
                        MYSQL_PASSWORD: 'swarna99@GB'
                ports:
                        - "3306:3306"
                volumes:
                        - dbdata:/var/lib/mysql

        app:
                depends_on:
                        - db
                build: src
                container_name: myapp
                ports:
                        - "5000:80"
                volumes:
                        - /var/www/html